### ISSUE TITLE
No error when logging in with bad username/pwd

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#19]
When you attempt to login to the site with bad credentials, there is no clear message to the user that your credentials are bad.

To reproduce:
1) Go to http://tackletrading.com
2) Click on Login in the upper-right corner
3) Login with a gibberish username and password
4) Note that login window closes and you are simply returned to the homepage

Expected behavior:
It should popup some text in RED within the login window saying something along the lines of, "I'm sorry, that username/password combination did not work. Please try to login again."

If you need this mocked up, let me know and I will do so.

**Comment by highwayjourney** [comment]
Resolved. Anyway, the message contents are little different.

**Comment by windupmicheal** [comment]
There's an error, but the formatting looks terrible on my macbook with chrome..

<img width="388" alt="2016-09-21 22 43 44" src="https://cloud.githubusercontent.com/assets/20033472/18738049/ecb05328-804c-11e6-882a-22e6a4ffc8c5.png">

**Comment by windupmicheal** [comment]
As per Leo (from Slack): "The current login system uses ontraport-registered membership. so it didn’t use built-in Wordpress login system and it needed some time to customize for ajax login. since we don’t have to submit data to form(if we submit data, the login dialog disappears as you know), I had to use ajax call  to check if the username and password are for valid user."

**Comment by highwayjourney** [comment]
I don't understand why length of inputbox differs from my Chrome, anyway, I've made the font smaller. Please check and let me know if the error message still overflows.

**Comment by windupmicheal** [comment]
Still seeing weird styling issues...

<img width="418" alt="2016-09-27 07 45 50" src="https://cloud.githubusercontent.com/assets/20033472/18878727/870ca3da-8486-11e6-8e18-d28fd9372afc.png">

**Comment by windupmicheal** [comment]
This is fixed on the staging site. Looks like my browser was caching an old stylesheet.

**Comment by windupmicheal** [comment]
This needs to be fixed again. The last fix worked, but the pilot press issue got in the way, I think? @highwayjourney , can you confirm?

**Comment by windupmicheal** [comment]
This is fixed!
